spring:
  datasource:
    username: test
    password: 123456
    url: jdbc:mysql://127.0.0.1:zjkb/mp_test?serverTimezone=UTC
mybatis-plus:
  mapper-locations: classpath:/mapper/*Mapper.xml
server:
  port: 80